baseurl = ""
disqusShortname = ""
languageCode = "en-US"
paginate = 6
theme = "casper-two"
[[menu.main]]
name = "Imprint"
url = "tags/imprint"
weight = 2
[[menu.main]]
name = "Search"
url = "https://google.com/"
weight = 1
[[menu.main]]
name = "Stories"
url = "/tags/Stories/"
weight = 2
[[menu.main]]
name = "Assets"
url = "/categories/assets/"
weight = 3
[[menu.main]]
name = "Functions"
url = "/tags/functions/"
weight = 4
[[menu.main]]
name = "Main"
url = "/"
weight = 5
[params]
author = "Andy"
authoravatar = "profil.png"
authordescription = "Tester"
authorlocation = "New York"
authorwebsite = ""
cover = "northern.jpg"
customcss = []
description = "Here is a description of your site."
fbname = ""
githubname = "ancahar2018"
googleanalytics = ""
logo = ""
metadescription = ""
orgdescription = "Here is a description placeholder for your org"
orgname = "AH"
orgwebsite = ""
pagenotfoundtitle = "404 - Page not found"
rsslink = ""
singleviewstyle = "casper"
subtitle = "Testing Netlify and Github"
title = "Excample Site"
twittername = ""
[permalinks]
post = "/:slug/"
